# Generated by Django 5.0.7 on 2024-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
