# Generated by Django 5.0.6 on 2024-06-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(max_length=20)),
                ('class_size', models.PositiveIntegerField()),
                ('class_rep', models.CharField(max_length=20)),
                ('enrollment', models.PositiveSmallIntegerField()),
                ('class_goal', models.PositiveSmallIntegerField()),
                ('class_vision', models.TextField(max_length=30)),
                ('class_id', models.CharField(max_length=15)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_meetings', models.CharField(max_length=10)),
            ],
        ),
    ]
