# Generated by Django 5.0.7 on 2024-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_goal',
            field=models.CharField(max_length=30),
        ),
    ]
